{% set name = "ptychodus" %}
{% set version = "0.7.3" %}

package:
  name: ptychodus-split
  version: {{ version }}

source:
  url: https://github.com/AdvancedPhotonSource/ptychodus/releases/download/v{{ version }}/ptychodus-v{{ version }}.zip
  sha256: c9a2d84d707ebda240dc43a40613a426d505f2b3b69ad91a9c0060a15c0fe6a9

build:
  number: 1
  skip: true  # [cuda_compiler_version != "12.0"]
  skip: true  # [cuda_compiler_version == "None"]

outputs:
  # all optional packages
  - name: ptychodus-all

    build:
      noarch: generic
      ignore_run_exports_from:
        - {{ compiler('cuda') }}

    requirements:
      build:
      # We don't need the compiler, just the __cuda virtual package
        - {{ compiler('cuda') }}
      run:
        - {{ pin_subpackage('ptychodus', exact=True) }}
        - gladier
        - gladier-tools
        - ptychonn
        - tike

    test:
      # no import test because tike imports cupy
      requires:
        - pip
      commands:
        - pip check
      # no CLI test because tike imports cupy

  # with QT
  - name: ptychodus

    build:
      noarch: generic

    requirements:
      run:
        - {{ pin_subpackage('ptychodus-core', exact=True) }}
        - pyqt

    test:
      imports:
        - ptychodus
      requires:
        - pip
      commands:
        - pip check
        - ptychodus --version

  # ptychodus without QT (headless) without optional packages
  - name: ptychodus-core

    script: build-core.sh

    build:
      noarch: python
      entry_points:
        - ptychodus = ptychodus.__main__:main
        - ptychodus_bdp = ptychodus.ptychodus_bdp:main

    requirements:
      host:
        - pip
        - python >=3.10
        - setuptools >=46.4.0
        - setuptools_scm >=7
        - setuptools_scm_git_archive
        - wheel
      run:
        - h5py =3.*
        - hdf5plugin
        - matplotlib-base =3.*
        - numpy =1.*
        - psutil =5.*
        - python >=3.10
        - scikit-image =0.*
        - scipy >=1.6,<2.0
        - tifffile =2023.*
        - watchdog =3.*
      run_constrained:
        - gladier >=0.9
        - gladier-tools >=0.5
        # pytorch is not a direct dependency, but we want to GPU version for ptychonn
        - pytorch=*=cuda*
        - ptychonn =0.2.*
        - pyqt =5.*
        - tike >=0.25.3,<0.26

    test:
      imports:
        - ptychodus
      requires:
        - pip
      commands:
        - pip check
        - ptychodus --version

about:
  home: https://github.com/AdvancedPhotonSource/ptychodus
  summary: Ptychodus is a ptychography analysis application.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/AdvancedPhotonSource/ptychodus

extra:
  recipe-maintainers:
    - AdvancedPhotonSource/ptychodus
    - carterbox
    - stevehenke
