{% set python_min = "3.10" %}
{% set name = "ptychodus" %}
{% set version = "1.0" %}

package:
  name: ptychodus-split
  version: {{ version }}

source:
  url: https://github.com/AdvancedPhotonSource/ptychodus/archive/refs/tags/v{{ version }}.zip
  sha256: 49382d24e5b3342f2ffd829f72b9255f3efc56340178fd935d9d79ade0009999

build:
  number: 0

outputs:
  # all optional packages
  - name: ptychodus-all

    build:
      noarch: generic

    requirements:
      run:
        - {{ pin_subpackage('ptychodus', exact=True) }}
        - gladier
        - gladier-tools
        - ptychonn
        - tike

    test:
      # no import test because tike imports cupy
      requires:
        - pip
      commands:
        - pip check
      # no CLI test because tike imports cupy

  # with QT
  - name: ptychodus

    build:
      noarch: generic

    requirements:
      run:
        - {{ pin_subpackage('ptychodus-core', exact=True) }}
        - pyqt

    test:
      imports:
        - ptychodus
      requires:
        - pip
      commands:
        - pip check
        - ptychodus --version

  # ptychodus without QT (headless) without optional packages
  - name: ptychodus-core

    script: build-core.sh

    build:
      noarch: python
      entry_points:
        - ptychodus = ptychodus.__main__:main
        - ptychodus_bdp = ptychodus.ptychodus_bdp:main

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools >=64
        - setuptools_scm >=8
        - setuptools_scm_git_archive
        - wheel
      run:
        - h5py
        - hdf5plugin
        - matplotlib-base
        - numpy
        - psutil
        - python >={{ python_min }}
        - scikit-image
        - scipy
        - tifffile
        - watchdog
      run_constrained:
        - gladier
        - gladier-tools
        - ptychonn =0.3.*,>=0.3.7
        - pyqt =5.*
        - tike >=0.25.3,<0.26

    test:
      imports:
        - ptychodus
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
        - ptychodus --version

about:
  home: https://github.com/AdvancedPhotonSource/ptychodus
  summary: Ptychodus is a ptychography data analysis application.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/AdvancedPhotonSource/ptychodus

extra:
  recipe-maintainers:
    - AdvancedPhotonSource/ptychodus
    - carterbox
    - stevehenke
